services:
  be-function:
    build:
      context: .
      target: php
    ports:
      - ${BE_FUNCTION_PORT}:8000
    volumes:
      - .:/var/task
    env_file:
      - .env
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
      APP_STAGE: local
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: dummy
      DYNAMODB_TABLE: app
      FEEDBACK_MEDIA_BUCKET: ${FEEDBACK_MEDIA_BUCKET:-feedbacks-local-media}
      TELEGRAM_ADMIN_ID: 0
      TELEGRAM_ACTIVITIES_TOKEN: 0:dummy
      TELEGRAM_ERRORS_TOKEN: 0:dummy
      GOOGLE_API_KEY: dummy
      CRYPTO: '{"btc":"btc-address","eth":"eth-address"}'
      SITE_BASE_URL: http://localhost:${BE_FUNCTION_PORT}
      DYNAMODB_ENDPOINT: http://dynamodb:8000

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - ${DYNAMODB_PORT}:8000
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    user: root

volumes:
  dynamodb-data:
